"""Add worker to jobs

Revision ID: 4ed115c365ec
Revises: 800715b40475
Create Date: 2026-08-11 01:55:49.693810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed115c365ec'
down_revision: Union[str, Sequence[str], None] = '800715b40475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'jobs', 'workers', ['worker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    # ### end Alembic commands ###
